# Generated by Django 5.0.6 on 2024-06-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=20)),
                ('stock_sys', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Salida',
                'db_table': 'Salida',
            },
        ),
        migrations.CreateModel(
            name='SalidaHistorico',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('usuario', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Salida Historico',
                'db_table': 'Salida Historico',
            },
        ),
    ]
