# Generated by Django 5.0.6 on 2024-06-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('stock_sys', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ingreso',
                'db_table': 'Ingreso',
            },
        ),
        migrations.CreateModel(
            name='IngresoHistorico',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('boleta', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('usuario', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Ingreso Historico',
                'db_table': 'Ingreso Historico',
            },
        ),
    ]
