# Generated by Django 5.0.6 on 2024-06-14 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=20)),
                ('movimiento', models.CharField(max_length=20)),
                ('ingreso', models.DateField()),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('categoria_nombre', models.CharField(max_length=30)),
                ('ubicacion_nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Historial',
                'db_table': 'Historial',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'db_table': 'Ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroproducto.categoria')),
                ('id_ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroproducto.ubicacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'db_table': 'Producto',
            },
        ),
    ]
