# Generated by Django 5.0.6 on 2024-06-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Inventario',
                'db_table': 'Inventario',
            },
        ),
    ]
