# Generated by Django 5.0.6 on 2024-06-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('modificación', models.DateField()),
                ('inventario', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'db_table': 'Empresa',
            },
        ),
    ]
